server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: census31-fwmt-tm-mocks
  security:
    user:
      name: "user"
      password: "password"
  jackson:
    date-format: uk.gov.ons.census.fwmt.tm.mock.config.RFC3339DateFormat
  cloud:
    gcp:
      project-id: fwmt-local
      credentials:
        enabled: false

management:
  # Place /info and /health in the root
  endpoints:
    web:
      base-path: ''
      exposure:
        include: health,info,env,refresh
  endpoint:
    health:
      show-details: always
    env:
      enabled: ${APP_TESTING:false}
      post:
        enabled: ${APP_TESTING:false}
    refresh:
      enabled: ${APP_TESTING:false}

logging:
  level:
    root: WARN
    uk.gov.ons.census.fwmt: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.amqp: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
    org.springframework: INFO
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] %logger{1}::%M - %msg%n"

customisation:
  logging:
    logFlagType:
      logAllMessages: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: uk.gov.ons.census.fwmt.tm.mock